language: node_js

node_js:
  - 0.12
  - 0.11
  - 0.10
  - 0.09
  - 0.08

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - export GULPBIN=./node_modules/gulp/bin/gulp.js

script:
  - ${GULPBIN} gulp-syntax-check
  - ${GULPBIN} integration_tests
  - ${GULPBIN} it.server
  - ${GULPBIN} it.runner
